package com.zhoujun.awegit.theme

import androidx.compose.ui.graphics.Color

val forkGraphLaneColors = listOf(
    Color(0xFF1F6FEB),
    Color(0xFFD93F0B),
    Color(0xFF2DA44E),
    Color(0xFF8250DF),
    Color(0xFFBF8700),
    Color(0xFFE85AAD),
    Color(0xFF0598BC),
    Color(0xFFCF222E),
    Color(0xFF57606A),
    Color(0xFF6639BA),
)

val lightTheme = ColorsScheme(
    primary = Color(0xFF0070D8),
    primaryVariant = Color(0xFF0070D8),
    onPrimary = Color(0xFFFFFFFFF),
    secondary = Color(0xFF9c27b0),
    onSecondary = Color(0xFFFFFFFF),
    onBackground = Color(0xFF212934),
    onBackgroundSecondary = Color(0xFF595858),
    error = Color(0xFFc93838),
    onError = Color(0xFFFFFFFF),
    background = Color(0xFFFFFFFF),
    backgroundSelected = Color(0xC0cee1f2),
    surface = Color(0xFFF8F8F8),
    secondarySurface = Color(0xFFE9ECEF),
    tertiarySurface = Color(0xFFE9ECEF),
    addFile = Color(0xFF32A852),
    deletedFile = Color(0xFFc93838),
    modifiedFile = Color(0xFF0070D8),
    conflictingFile = Color(0xFFFFB638),
    dialogOverlay = Color(0xAA000000),
    normalScrollbar = Color(0xFFCCCCCC),
    hoverScrollbar = Color(0xFF0070D8),
    diffLineAdded = Color(0xAAd7ebd0),
    diffContentAdded = Color(0x4570df70),
    diffLineRemoved = Color(0xAAf0d4d4),
    diffContentRemoved = Color(0x45FF0000),
    diffKeyword = Color(0xff3b83cf),
    diffAnnotation = Color(0xff9f9927),
    diffComment = Color(0xff0d9141),
    isLight = true,
)


val darkTheme = ColorsScheme(
    primary = Color(0xFF0169cb),
    primaryVariant = Color(0xFF9FD1FF),
    onPrimary = Color(0xFFFFFFFFF),
    secondary = Color(0xFFe9c754),
    onSecondary = Color(0xFF0E1621),
    onBackground = Color(0xFFFFFFFF),
    onBackgroundSecondary = Color(0xFFCCCBCB),
    error = Color(0xFFc93838),
    onError = Color(0xFFFFFFFF),
    background = Color(0xff0F0F0F),
    backgroundSelected = Color(0xFF2f3640),
    surface = Color(0xFF1F1F22),
    secondarySurface = Color(0xFF1a2b3d),
    tertiarySurface = Color(0xFF0a335c),
    addFile = Color(0xFF32A852),
    deletedFile = Color(0xFFc93838),
    modifiedFile = Color(0xFF0070D8),
    conflictingFile = Color(0xFFFFB638),
    dialogOverlay = Color(0xAA000000),
    normalScrollbar = Color(0xFF888888),
    hoverScrollbar = Color(0xFFCCCCCC),
    diffLineAdded = Color(0xAA566f5a),
    diffContentAdded = Color(0x4500FF00),
    diffLineRemoved = Color(0xAA6f585e),
    diffContentRemoved = Color(0x45FF0000),
    diffKeyword = Color(0xffa3caf1),
    diffAnnotation = Color(0xFFB3AE5F),
    diffComment = Color(0xFF70C290),
    isLight = false,
)

private fun forkBase(
    isLight: Boolean,
    background: Color,
    surface: Color,
    sidebarBackground: Color,
    toolbarBackground: Color,
    border: Color,
    primary: Color,
    backgroundSelected: Color,
    selectionUnfocused: Color,
    onBackground: Color,
    onBackgroundSecondary: Color,
    diffLineAdded: Color,
    diffContentAdded: Color,
    diffLineRemoved: Color,
    diffContentRemoved: Color,
    badgeLocal: Color,
    badgeRemote: Color,
    badgeTag: Color,
    badgeStash: Color,
    addFile: Color = Color(0xFF2DA44E),
    modifiedFile: Color = Color(0xFFBF8700),
    deletedFile: Color = Color(0xFFCF222E),
    conflictingFile: Color = Color(0xFFD1242F),
) = ColorsScheme(
    primary = primary,
    primaryVariant = primary,
    onPrimary = Color.White,
    secondary = primary,
    onSecondary = Color.White,
    onBackground = onBackground,
    onBackgroundSecondary = onBackgroundSecondary,
    error = Color(0xFFCF222E),
    onError = Color.White,
    background = background,
    backgroundSelected = backgroundSelected,
    surface = surface,
    secondarySurface = sidebarBackground,
    tertiarySurface = toolbarBackground,
    addFile = addFile,
    deletedFile = deletedFile,
    modifiedFile = modifiedFile,
    conflictingFile = conflictingFile,
    dialogOverlay = Color(0xAA000000),
    normalScrollbar = border,
    hoverScrollbar = onBackgroundSecondary,
    diffLineAdded = diffLineAdded,
    diffContentAdded = diffContentAdded,
    diffLineRemoved = diffLineRemoved,
    diffContentRemoved = diffContentRemoved,
    diffKeyword = primary,
    diffAnnotation = modifiedFile,
    diffComment = addFile,
    isLight = isLight,
    border = border,
    sidebarBackground = sidebarBackground,
    toolbarBackground = toolbarBackground,
    selectionUnfocused = selectionUnfocused,
    badgeLocal = badgeLocal,
    badgeRemote = badgeRemote,
    badgeTag = badgeTag,
    badgeStash = badgeStash,
    graphLaneColors = forkGraphLaneColors,
)

val forkLightTheme = forkBase(
    isLight = true,
    background = Color(0xFFFFFFFF),
    surface = Color(0xFFFFFFFF),
    sidebarBackground = Color(0xFFF3F3F3),
    toolbarBackground = Color(0xFFEBEBEB),
    border = Color(0xFFD9D9D9),
    primary = Color(0xFF0067C0),
    backgroundSelected = Color(0xFFCCE4F7),
    selectionUnfocused = Color(0xFFE5E5E5),
    onBackground = Color(0xFF1A1A1A),
    onBackgroundSecondary = Color(0xFF6E6E6E),
    diffLineAdded = Color(0xFFE6FFEC),
    diffContentAdded = Color(0xFFABF2BC),
    diffLineRemoved = Color(0xFFFFEBE9),
    diffContentRemoved = Color(0xFFFFC1C0),
    badgeLocal = Color(0xFFDCEBFF),
    badgeRemote = Color(0xFFEAEAEA),
    badgeTag = Color(0xFFFFF1C2),
    badgeStash = Color(0xFFEDE3FF),
)

val forkDarkTheme = forkBase(
    isLight = false,
    background = Color(0xFF262626),
    surface = Color(0xFF2B2B2B),
    sidebarBackground = Color(0xFF2B2B2B),
    toolbarBackground = Color(0xFF323232),
    border = Color(0xFF3C3C3C),
    primary = Color(0xFF3794FF),
    backgroundSelected = Color(0xFF2F4F6F),
    selectionUnfocused = Color(0xFF3A3A3A),
    onBackground = Color(0xFFE6E6E6),
    onBackgroundSecondary = Color(0xFF9D9D9D),
    diffLineAdded = Color(0xFF1E3A24),
    diffContentAdded = Color(0xFF2E5E37),
    diffLineRemoved = Color(0xFF4A1F1F),
    diffContentRemoved = Color(0xFF7A2F2F),
    badgeLocal = Color(0x4DDCEBFF),
    badgeRemote = Color(0x4DEAEAEA),
    badgeTag = Color(0x4DFFF1C2),
    badgeStash = Color(0x4DEDE3FF),
)

